
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from './components/Navbar'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Cre8-ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div data-theme="sunset" className="h-screen">
        <Navbar/>
        {children}
        </div>
      </body>
    </html>
    </ClerkProvider>
   
  );
}
